name: CI
on:
  push:
    branches: [$default-branch]
  pull_request:
jobs:
  test:
    name: tests / ruby
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    strategy:
      matrix:
        ruby-version: ['2.7.7', '3.0']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1.133.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          cache-version: 1
      - name: Install dependencies
        run: bundle install --jobs 4
      - name: Run tests
        run: bundle exec rake
  rubocop:
    name: linters / rubocop
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 2.7.7
    steps:
      - name: Codebase Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.133.0
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          cache-version: 1

      - name: rubocop
        run: bundle exec rubocop
